### PR TITLE
Update OBSVideoCapture.cpp

### PR DESCRIPTION
**Pull request by jinhwang15**

### CODE REVIEW

**Comment by sir-ragna** [comment]
You should probably add pull requests #461 and #460  into one and provide a title and a description.

At line https://github.com/jp9000/OBS/pull/460/files#diff-c15ccc4d9faddaa53a2bae673a42575aR1431 you call malloc but you don't call free in the same scope. Don't you introduce a memory leak by that? (I'm asking as I don't write C++ myself.)

**Comment by jackun** [comment]
Yes. Also sizeof(char*) == [ 4 || 8 ] depending on cpu architecture. Correct would be to just use `char array[64];`

**Comment by Heufneutje** [comment]
Not to mention this part of the README:

> Outside of simple and specific bug fixes, pull requests for this version of OBS are unlikely to receive review - we encourage you to spend your time developing for OBS MP instead.

**Comment by notr1ch** [comment]
Seems to lack any purpose and we don't really want to be adding or supporting new features to OBS classic.

**Pull request closed without merging**
