### PR TITLE
Add new stream service

### PR DESCRIPTION
**Pull request by CyberSlimp**
Please add new stream service reall.tv by team of cybergame.tv.
Thank You.

### CODE REVIEW

**Comment by notr1ch** [comment]
Hello,
We no longer accept new submissions for OBS 1. Please create a .obs-service file as described in edfbea5ba06282d68c298a6b406d6b7c678c5701 or use our web service at https://obsproject.com/services/add

**Comment by CyberSlimp** [comment]
Hello. I make 2 files via https://obsproject.com/services/add , fist (ReAll) without settings, and its file not work (make OBS crash), second (reall.tv) with settings - works correctly, can u add to public service from second file? Thank You.

**Comment by notr1ch** [comment]
The services file is for your users to download, it will then import into their local OBS installation.

**Comment by CyberSlimp** [comment]
Can You add our stream settings to default installation of OBS?

**Comment by Jack0r** [comment]
You already got the answer to that question:
"We no longer accept new submissions for OBS 1. Please create a .obs-service file as described in edfbea5 or use our web service at https://obsproject.com/services/add"

**Pull request closed without merging**
