### PR TITLE
Experimental asynchronous render / encode support

### PR DESCRIPTION
**Pull request by Eleuria**
Fixes "frozen stream" effect when the encoder gets behind, greatly increases performance for slow scenes. x264 only for now. CFR, audio sync untested. Likely other bugs.

### CODE REVIEW

**Comment by notr1ch** [comment]
OBS Classic is no longer under development.

**Comment by Poliwrath** [comment]
ok

**Comment by P5-2p** [comment]
const {a=1, b=2} = {a:2};

**Comment by P5-2p** [comment]
Obs

**Comment by P5-2p** [comment]
Facebook

**Pull request closed without merging**
